### ISSUE TITLE
Changes to site config access

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ffh-packages#3]
Hi,
we have recently pushed a new Lua library for site access. This new library
allows more convenient access to nested optional values:

>     gluon-core: add new gluon.site library for convenient access to optional values
>     
>     The new gluon.site lua library will eventually replace gluon.site_config
>     (which is hereby deprecated, but will continue to be supported for a
>     while).
>     
>     The new gluon.site library will wrap all values to allow traversing
>     non-existing tables without errors.
>     
>         site = require 'gluon.site'
>         c = site.a.b.c -- doesn't fail even if a or a.b don't exist
>     
>     The wrapped values must be unwrapped using call syntax:
>     
>         site_name = site.site_name()
>     
>     Using the call syntax on a non-existing value will return nil. An
>     alternative default value may be passed instead:
>     
>         mac = site.next_node.mac('16:41:95:40:f7:dc')

At the moment, both libaries are available for use in custom packages, but
the old gluon.site_config library will be removed soon.

Site i18n files that access the site configuration from Lua code in the
gluon-config-mode:reboot, gluon-config-mode:pubkey or
gluon-config-mode:novpn messages need to be adjusted, as the config mode
wizard now uses the new site library.

-- NeoRaider

**Comment by 1977er** [comment]
Müssen wir unsere district Sachen umstricken?

**Comment by lemoer** [comment]
No longer relevant...
